/* The nine precompiles against an independent implementation on random inputs (Task 6, ruling 3):
 * precompile_fuzz_vectors.h is generated by gen_precompile_fuzz.py from a fixed seed with py_ecc,
 * pycryptodome, hashlib, Python's pow and RFC 7693's F (that script's docstring lists the cases:
 * random signatures and their corruptions, random hash inputs, random modexp operands, multiples of
 * the alt_bn128 generators, a pairing product that is 1 and one that is not, blake2f at 0..24
 * rounds, and the invalid encodings of each). For every vector: RequiredGas, and the run's
 * success and exact output, or its failure. */
#include <stdlib.h>
#include <string.h>
#include "test.h"
#include "../precompiles.h"
#include "precompile_fuzz_vectors.h"

extern int t_real_keccak;

static uint8_t *unhex(const char *s, uint32_t *n) {
    size_t l = strlen(s);
    *n = (uint32_t)(l / 2);
    uint8_t *b = malloc(*n + 1);
    for (uint32_t i = 0; i < *n; i++) {
        unsigned v;
        sscanf(s + 2 * i, "%2x", &v);
        b[i] = (uint8_t)v;
    }
    return b;
}

static uint8_t out[PC_OUT_MAX];

int precompile_fuzz_tests(void) {
    t_real_keccak = 1;
    uint32_t per_addr[10] = {0};
    size_t n = sizeof PC_FUZZ / sizeof *PC_FUZZ;
    for (size_t k = 0; k < n; k++) {
        const pc_fuzz_vector *v = &PC_FUZZ[k];
        uint32_t in_len, want_len;
        uint8_t *in = unhex(v->in, &in_len);
        uint8_t *want = unhex(v->out, &want_len);
        uint64_t gas = evm_precompile_gas(v->addr, in, in_len);
        if (gas != v->gas)
            fprintf(stderr, "  %s: gas %llu, want %llu\n", v->name, (unsigned long long)gas, v->gas);
        CHECK(gas == v->gas);
        uint32_t out_len = 0xdead;
        uint32_t r = evm_precompile_run(v->addr, in, in_len, out, &out_len);
        int good = v->ok ? (r == PC_OK && out_len == want_len && memcmp(out, want, want_len) == 0)
                         : r == PC_FAIL;
        if (!good) fprintf(stderr, "  %s: r %u, out_len %u (want %u)\n", v->name, r, out_len, want_len);
        CHECK(good);
        per_addr[v->addr]++;
        free(in);
        free(want);
    }
    for (int a = 1; a <= 9; a++) CHECK(per_addr[a] >= 5);
    t_real_keccak = 0;
    printf("precompile fuzz: %zu vectors\n", n);
    return 0;
}
